version: '3'

services:
  db:
    environment:
      POSTGRES_DB: TCSQSS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    image: postgres:9.5
    expose:
      - "5432"
    ports:
      - "5432:5432"
